version: 2.1

orbs:
  hello-world: sample-orbs/hello-world@0.0.10

jobs:
  integration-test-1:
    environment:
      FOO: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    parameters:
      foo:
        type: env_var_name
        default: FOO
    docker:
      - image: cimg/python:3.9
    steps:
      - run:
          command: |
            echo ${<<parameters.foo>>}
      - hello-world/echo-command:
          to: ${<<parameters.foo>>}

workflows:
  integration-test_deploy:
    jobs:
      - integration-test-1
