version: 2.1

orbs:
  hello-world: sample-orbs/hello-world@0.0.10
  aws-sg-white-list-circleci-ip: inokappa/aws-sg-white-list-circleci-ip@dev:alpha

jobs:
  integration-test-1:
    environment:
      FOO: '123'
    parameters:
      foo:
        type: env_var_name
        default: FOO
      bar:
        type: string
        default: 'test'
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          command: |
            echo ${<<parameters.foo>>}
      - run:
          command: |
            echo "export FOO=aaaaaaaaaaaaaaaaaaaaaaaaaaaa" >> ${BASH_ENV}
      - hello-world/echo-command:
          to: ${<<parameters.foo>>}
      - aws-sg-white-list-circleci-ip/add:
          group-id: ${<<parameters.foo>>}
      - aws-sg-white-list-circleci-ip/del:
          group-id: ${<<parameters.bar>>}

#
workflows:
  integration-test_deploy:
    jobs:
      - integration-test-1
