version: 2.1

orbs:
  aws-sg-white-list-circleci-ip: inokappa/aws-sg-white-list-circleci-ip@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0
  bats: circleci/bats@1.0
  shellcheck: circleci/shellcheck@2.0

parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

executors:
  integration-test:
    docker:
      - image: cimg/python:3.9
        environment:
          AWS_ACCESS_KEY_ID: EXAMPLEKEY123
          AWS_SECRET_ACCESS_KEY: EXAMPLESECRET123456
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION: us-east-1
          AWS_ENDPOINT: http://moto-server:5000
          AWS_DISABLE_SSL: true
      - image: motoserver/moto
        name: moto-server
        command: ["ec2", "-H", "0.0.0.0"]

commands:
  install-awscli:
    steps:
      - run:
          name: Install awscli
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
              unzip awscliv2.zip && \
              sudo ./aws/install

  create-security-group:
    steps:
      - run:
          name: Create Security Group
          command: |
            SG_ID=$(aws --endpoint ${AWS_ENDPOINT} ec2 \
              create-security-group --group-name MySecurityGroup --description "My security group" \
            | jq -r '.GroupId')
            echo "export GROUP_ID=${SG_ID}" >> $BASH_ENV
            aws --endpoint ${AWS_ENDPOINT} ec2 \
              create-tags --resources ${SG_ID} --tags Key=sg-white-list,Value=true

  check-exists-ip-permission:
    steps:
      - run:
          name: Check exists IP Permission in Security Group
          command: |
            COUNT=$(aws --endpoint ${AWS_ENDPOINT} ec2 describe-security-groups --group-ids ${GROUP_ID} \
                    | jq '.SecurityGroups[].IpPermissions|length')
            if [ $COUNT != 1 ];then
              exit 1
            fi

  check-not-exists-ip-permission:
    steps:
      - run:
          name: Check not exists IP Permission in Security Group
          command: |
            COUNT=$(aws --endpoint ${AWS_ENDPOINT} ec2 describe-security-groups --group-ids ${GROUP_ID} \
                    | jq '.SecurityGroups[].IpPermissions|length')
            if [ $COUNT != 0 ];then
              exit 1
            fi

jobs:
  integration-test-1:
    environment:
      AWS_PAGER: ''
      GROUP_ID: ''
    parameters:
      group-id:
        type: env_var_name
        default: GROUP_ID
    executor: integration-test
    steps:
      - checkout
      - install-awscli
      - create-security-group
      - aws-sg-white-list-circleci-ip/add:
          group-id: ${<< parameters.group-id >>}
      - check-exists-ip-permission
      - aws-sg-white-list-circleci-ip/del:
          group-id: ${<< parameters.group-id >>}
      - check-not-exists-ip-permission

  integration-test-2:
    environment:
      AWS_PAGER: ''
      GROUP_ID: ''
    executor: integration-test
    steps:
      - checkout
      - install-awscli
      - create-security-group
      - aws-sg-white-list-circleci-ip/add:
          tag-key: 'sg-white-list'
          tag-value: 'true'
      - check-exists-ip-permission
      - aws-sg-white-list-circleci-ip/del:
          tag-key: 'sg-white-list'
          tag-value: 'true'
      - check-not-exists-ip-permission

  integration-test-3:
    environment:
      AWS_PAGER: ''
      GROUP_ID: ''
    parameters:
      group-id:
        type: env_var_name
        default: GROUP_ID
    executor: integration-test
    steps:
      - checkout
      - install-awscli
      - create-security-group
      - aws-sg-white-list-circleci-ip/add:
          group-id: ${<< parameters.group-id >>}
          description: 'Test-Permission'
      - check-exists-ip-permission
      - run:
          name: Check description IP Permission in Security Group
          command: |
            DESC=$(aws --endpoint ${AWS_ENDPOINT} ec2 describe-security-groups --group-ids ${GROUP_ID} \
                    | jq -r '.SecurityGroups[].IpPermissions[0].IpRanges[0].Description')
            if [ "${DESC}" != "Test-Permission" ];then
              exit 1
            fi
      - aws-sg-white-list-circleci-ip/del:
          group-id: ${<< parameters.group-id >>}
          description: 'Test-Permission'
      - check-not-exists-ip-permission

  integration-test-4:
    environment:
      AWS_PAGER: ''
      GROUP_ID: ''
    executor: integration-test
    steps:
      - checkout
      - install-awscli
      - create-security-group
      - aws-sg-white-list-circleci-ip/add:
          tag-key: 'sg-white-list'
          tag-value: 'true'
          port: 22
      - check-exists-ip-permission
      - run:
          name: Check ports IP Permission in Security Group
          command: |
            PORTS=$(aws --endpoint ${AWS_ENDPOINT} ec2 describe-security-groups --group-ids ${GROUP_ID} \
                    | jq -r '.SecurityGroups[0].IpPermissions[0]|[.FromPort, .ToPort]|@csv')
            if [ "${PORTS}" != "22,22" ];then
              exit 1
            fi
      - aws-sg-white-list-circleci-ip/del:
          tag-key: 'sg-white-list'
          tag-value: 'true'
          port: 22
      - check-not-exists-ip-permission

  integration-test-5:
    environment:
      AWS_PAGER: ''
      GROUP_ID: ''
    executor: integration-test
    steps:
      - checkout
      - install-awscli
      - create-security-group
      - aws-sg-white-list-circleci-ip/add:
          tag-key: 'sg-white-list'
          tag-value: 'true'
          port: 22
      - check-exists-ip-permission
      - run:
          name: Command failure
          command: |
            echo 'Command failure.'
            exit 1
      - aws-sg-white-list-circleci-ip/del:
          tag-key: 'sg-white-list'
          tag-value: 'true'
          port: 22
      - check-not-exists-ip-permission

workflows:
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - shellcheck/check:
          dir: ./src/scripts
          exclude: SC2148,SC1091,SC2046,SC2086,SC2016,SC1090
      - bats/run:
          path: ./src/tests
      - hold-for-dev-publish:
          type: approval
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - bats/run
            - shellcheck/check
      - orb-tools/publish-dev:
          orb-name: inokappa/aws-sg-white-list-circleci-ip
          context: orb-publishing
          requires: [hold-for-dev-publish]
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          requires:
            - orb-tools/publish-dev

  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - integration-test-1
      - integration-test-2
      - integration-test-3
      - integration-test-4
      - integration-test-5
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: inokappa/aws-sg-white-list-circleci-ip
          context: orb-publishing
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          requires:
            - integration-test-1
            - integration-test-2
            - integration-test-3
            - integration-test-4
            - integration-test-5
          filters:
            branches:
              only:
                - master
                - main
