version: 2.1

orbs:
  aws-sg-white-list-circleci-ip: inokappa/aws-sg-white-list-circleci-ip@dev:alpha

jobs:
  integration-test-1:
    environment:
      GROUP_ID: '1xxxxxxxxxxxxxxxxxxxxxxxxxxxx'
      FOO: '1xxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    parameters:
      group-id:
        type: env_var_name
        default: FOO
    docker:
      - image: cimg/python:3.9
        environment:
          AWS_ACCESS_KEY_ID: EXAMPLEKEY123
          AWS_SECRET_ACCESS_KEY: EXAMPLESECRET123456
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION: us-east-1
          AWS_ENDPOINT: http://moto-server:5000
          AWS_DISABLE_SSL: true
    steps:
      - checkout
      - run:
          name: Test
          command: |
            echo ${<<parameters.group-id>>}
      - aws-sg-white-list-circleci-ip/add:
          group-id: <<parameters.group-id>>

workflows:
  test-pack:
    jobs:
      - integration-test-1
